; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35227.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__8C83BECC_concurrencysal@h DB 01H
__608E3340_sal@h DB 01H
__FB67E29A_vadefs@h DB 01H
__1D1B619C_vcruntime@h DB 01H
__735960E1_corecrt@h DB 01H
__60B45B40_corecrt_stdio_config@h DB 01H
__CFA3741E_corecrt_wstdio@h DB 01H
__B3FE3303_stdio@h DB 01H
__13DE2371_errno@h DB 01H
__8C6AE390_vcruntime_string@h DB 01H
__8ACB2152_corecrt_memcpy_s@h DB 01H
__EA6C9D17_corecrt_memory@h DB 01H
__0DF2AF52_corecrt_wstring@h DB 01H
__6E889ECC_string@h DB 01H
__B7B53233_stdarg@h DB 01H
__695E8301_lprintf@h DB 01H
__777D71FB_protocol@h DB 01H
__A995AB26_datalink@h DB 01H
__3E4772AE_datalink@c DB 01H
msvcjmc	ENDS
PUBLIC	main
PUBLIC	__JustMyCode_Default
PUBLIC	??_C@_0BI@GICFHJCA@Send?5DATA?5?$CFd?5?$CFd?0?5ID?5?$CFd?6@ ; `string'
PUBLIC	??_C@_0O@MEIGFFMO@Send?5ACK?5?5?$CFd?6@		; `string'
PUBLIC	??_C@_0BD@FIILIENI@Retransmit?5seq?$DN?$CFd?6@	; `string'
PUBLIC	??_C@_0DI@MEIAPCCJ@Designed?5by?5Jiang?5Yanjun?0?5build@ ; `string'
PUBLIC	??_C@_0L@KKPDPFNK@CRC?5error?6@			; `string'
PUBLIC	??_C@_0CC@KIILNDNP@Recv?5DATA?5seq?$DN?$CFd?5ack?$DN?$CFd?5pktID?$DN?$CF@ ; `string'
PUBLIC	??_C@_0BB@KGDEPFAN@Recv?5ACK?5ack?$DN?$CFd?6@	; `string'
PUBLIC	??_C@_0BG@CGEOBPGK@?9?9?9?9?5DATA?5?$CFd?5timeout?6@ ; `string'
EXTRN	__report_rangecheckfailure:PROC
EXTRN	memcpy:PROC
EXTRN	lprintf:PROC
EXTRN	protocol_init:PROC
EXTRN	wait_for_event:PROC
EXTRN	enable_network_layer:PROC
EXTRN	disable_network_layer:PROC
EXTRN	get_packet:PROC
EXTRN	put_packet:PROC
EXTRN	recv_frame:PROC
EXTRN	send_frame:PROC
EXTRN	crc32:PROC
EXTRN	start_timer:PROC
EXTRN	stop_timer:PROC
EXTRN	dbg_event:PROC
EXTRN	dbg_frame:PROC
EXTRN	_RTC_CheckStackVars:PROC
EXTRN	_RTC_InitBase:PROC
EXTRN	_RTC_Shutdown:PROC
EXTRN	__CheckForDebuggerJustMyCode:PROC
EXTRN	__GSHandlerCheck:PROC
EXTRN	__security_check_cookie:PROC
EXTRN	__security_cookie:QWORD
_BSS	SEGMENT
buffer	DB	0100H DUP (?)
window_buzy DB	01H DUP (?)
	ALIGN	4

acked_seq DB	01H DUP (?)
	ALIGN	4

next_seq_to_send DB 01H DUP (?)
	ALIGN	4

send_buffer DB	08400H DUP (?)
timer_active DB	080H DUP (?)
excepted_seq DB	01H DUP (?)
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$put_frame DD imagerel put_frame
	DD	imagerel put_frame+115
	DD	imagerel $unwind$put_frame
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$send_data_frame DD imagerel send_data_frame
	DD	imagerel send_data_frame+275
	DD	imagerel $unwind$send_data_frame
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$send_ack_frame DD imagerel send_ack_frame
	DD	imagerel send_ack_frame+162
	DD	imagerel $unwind$send_ack_frame
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$seq_between DD imagerel seq_between
	DD	imagerel seq_between+200
	DD	imagerel $unwind$seq_between
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$retransmit_all DD imagerel retransmit_all
	DD	imagerel retransmit_all+267
	DD	imagerel $unwind$retransmit_all
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$main DD	imagerel $LN32
	DD	imagerel $LN32+1002
	DD	imagerel $unwind$main
pdata	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
_RTC_Shutdown.rtc$TMZ DQ FLAT:_RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
_RTC_InitBase.rtc$IMZ DQ FLAT:_RTC_InitBase
rtc$IMZ	ENDS
;	COMDAT ??_C@_0BG@CGEOBPGK@?9?9?9?9?5DATA?5?$CFd?5timeout?6@
CONST	SEGMENT
??_C@_0BG@CGEOBPGK@?9?9?9?9?5DATA?5?$CFd?5timeout?6@ DB '---- DATA %d tim'
	DB	'eout', 0aH, 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0BB@KGDEPFAN@Recv?5ACK?5ack?$DN?$CFd?6@
CONST	SEGMENT
??_C@_0BB@KGDEPFAN@Recv?5ACK?5ack?$DN?$CFd?6@ DB 'Recv ACK ack=%d', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CC@KIILNDNP@Recv?5DATA?5seq?$DN?$CFd?5ack?$DN?$CFd?5pktID?$DN?$CF@
CONST	SEGMENT
??_C@_0CC@KIILNDNP@Recv?5DATA?5seq?$DN?$CFd?5ack?$DN?$CFd?5pktID?$DN?$CF@ DB 'R'
	DB	'ecv DATA seq=%d ack=%d pktID=%d', 0aH, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@KKPDPFNK@CRC?5error?6@
CONST	SEGMENT
??_C@_0L@KKPDPFNK@CRC?5error?6@ DB 'CRC error', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0DI@MEIAPCCJ@Designed?5by?5Jiang?5Yanjun?0?5build@
CONST	SEGMENT
??_C@_0DI@MEIAPCCJ@Designed?5by?5Jiang?5Yanjun?0?5build@ DB 'Designed by '
	DB	'Jiang Yanjun, build: May 16 2026  01:15:59', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BD@FIILIENI@Retransmit?5seq?$DN?$CFd?6@
CONST	SEGMENT
??_C@_0BD@FIILIENI@Retransmit?5seq?$DN?$CFd?6@ DB 'Retransmit seq=%d', 0aH
	DB	00H						; `string'
CONST	ENDS
;	COMDAT ??_C@_0O@MEIGFFMO@Send?5ACK?5?5?$CFd?6@
CONST	SEGMENT
??_C@_0O@MEIGFFMO@Send?5ACK?5?5?$CFd?6@ DB 'Send ACK  %d', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BI@GICFHJCA@Send?5DATA?5?$CFd?5?$CFd?0?5ID?5?$CFd?6@
CONST	SEGMENT
??_C@_0BI@GICFHJCA@Send?5DATA?5?$CFd?5?$CFd?0?5ID?5?$CFd?6@ DB 'Send DATA'
	DB	' %d %d, ID %d', 0aH, 00H			; `string'
CONST	ENDS
_DATA	SEGMENT
phl_ready DD	01H
_DATA	ENDS
;	COMDAT voltbl
voltbl	SEGMENT
_volmd	DW	039H
	DW	03d1H
voltbl	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$main DD	025054019H
	DD	01122317H
	DD	0700b007bH
	DD	0500aH
	DD	imagerel __GSHandlerCheck
	DD	03c8H
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
main$rtcName$0 DB 061H
	DB	072H
	DB	067H
	DB	00H
main$rtcName$1 DB 066H
	DB	00H
	ORG $+10
main$rtcVarDesc DD 070H
	DD	0108H
	DQ	FLAT:main$rtcName$1
	DD	044H
	DD	04H
	DQ	FLAT:main$rtcName$0
	ORG $+96
main$rtcFrameData DD 02H
	DD	00H
	DQ	FLAT:main$rtcVarDesc
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$retransmit_all DD 025050f01H
	DD	010a230fH
	DD	070030029H
	DD	05002H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$seq_between DD 025051b01H
	DD	0116231bH
	DD	0700f001fH
	DD	0500eH
xdata	ENDS
;	COMDAT voltbl
voltbl	SEGMENT
_volmd	DB	035H
	DB	089H
voltbl	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$send_ack_frame DD 025053c19H
	DD	010d2312H
	DD	070060043H
	DD	05005H
	DD	imagerel __GSHandlerCheck
	DD	0208H
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
send_ack_frame$rtcName$0 DB 073H
	DB	00H
	ORG $+14
send_ack_frame$rtcVarDesc DD 030H
	DD	0108H
	DQ	FLAT:send_ack_frame$rtcName$0
	ORG $+48
send_ack_frame$rtcFrameData DD 01H
	DD	00H
	DQ	FLAT:send_ack_frame$rtcVarDesc
CONST	ENDS
;	COMDAT voltbl
voltbl	SEGMENT
_volmd	DB	02bH
	DB	0f9H
voltbl	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$send_data_frame DD 025063219H
	DD	010b2310H
	DD	070040042H
	DD	050026003H
	DD	imagerel __GSHandlerCheck
	DD	0208H
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
send_data_frame$rtcName$0 DB 073H
	DB	00H
	ORG $+14
send_data_frame$rtcVarDesc DD 030H
	DD	0108H
	DQ	FLAT:send_data_frame$rtcName$0
	ORG $+48
send_data_frame$rtcFrameData DD 01H
	DD	00H
	DQ	FLAT:send_data_frame$rtcVarDesc
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$put_frame DD 025051701H
	DD	01122317H
	DD	0700b001dH
	DD	0500aH
xdata	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\Users\34021\Downloads\Lab1(Win+Linux)\Lab1-2024(Win+Linux)\Lab1-Windows-VS2019\datalink.c
;	COMDAT main
_TEXT	SEGMENT
event$ = 4
arg$ = 36
f$ = 80
len$ = 372
has_packet$ = 404
len$5 = 436
ack_num$6 = 468
s$7 = 500
$T8 = 920
tv69 = 932
__$ArrayPad$ = 936
argc$ = 976
argv$ = 984
main	PROC						; COMDAT

; 106  : {

$LN32:
	mov	QWORD PTR [rsp+16], rdx
	mov	DWORD PTR [rsp+8], ecx
	push	rbp
	push	rdi
	sub	rsp, 984				; 000003d8H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rdi, QWORD PTR [rsp+32]
	mov	ecx, 142				; 0000008eH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	ecx, DWORD PTR [rsp+1016]
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rbp
	mov	QWORD PTR __$ArrayPad$[rbp], rax
	lea	rcx, OFFSET FLAT:__3E4772AE_datalink@c
	call	__CheckForDebuggerJustMyCode
	npad	1

; 107  : 	int event, arg;
; 108  : 	struct FRAME f;
; 109  : 	int len = 0;

	mov	DWORD PTR len$[rbp], 0

; 110  : 	int has_packet = 0;

	mov	DWORD PTR has_packet$[rbp], 0

; 111  : 
; 112  : 	protocol_init(argc, argv);

	mov	rdx, QWORD PTR argv$[rbp]
	mov	ecx, DWORD PTR argc$[rbp]
	call	protocol_init
	npad	1

; 113  : 	lprintf("Designed by Jiang Yanjun, build: " __DATE__ "  "__TIME__

	lea	rcx, OFFSET FLAT:??_C@_0DI@MEIAPCCJ@Designed?5by?5Jiang?5Yanjun?0?5build@
	call	lprintf
	npad	1

; 114  : 		"\n");
; 115  : 
; 116  : 	disable_network_layer();

	call	disable_network_layer
	npad	1
$LN2@main:

; 117  : 
; 118  : 	for (;;) {
; 119  : 		event = wait_for_event(&arg);

	lea	rcx, QWORD PTR arg$[rbp]
	call	wait_for_event
	mov	DWORD PTR event$[rbp], eax

; 120  : 
; 121  : 		switch (event) {

	mov	eax, DWORD PTR event$[rbp]
	mov	DWORD PTR tv69[rbp], eax
	cmp	DWORD PTR tv69[rbp], 0
	je	SHORT $LN10@main
	cmp	DWORD PTR tv69[rbp], 1
	je	$LN13@main
	cmp	DWORD PTR tv69[rbp], 2
	je	$LN16@main
	cmp	DWORD PTR tv69[rbp], 3
	je	$LN26@main
	jmp	$LN5@main
$LN10@main:

; 122  : 		case NETWORK_LAYER_READY:   //网络层ready
; 123  : 			get_packet(buffer);  //此处依旧使用buffer读取帧，不修改原来的send_data_frame函数使用buffer的操作

	lea	rcx, OFFSET FLAT:buffer
	call	get_packet
	npad	1

; 124  : 			has_packet = 1;

	mov	DWORD PTR has_packet$[rbp], 1

; 125  : 
; 126  : 			if (!window_buzy&&phl_ready)

	movzx	eax, BYTE PTR window_buzy
	test	eax, eax
	jne	SHORT $LN11@main
	cmp	DWORD PTR phl_ready, 0
	je	SHORT $LN11@main

; 127  : 			{
; 128  : 				send_data_frame();

	call	send_data_frame
	npad	1

; 129  : 				next_seq_to_send = (next_seq_to_send + 1) % MAX_SEQ;

	movzx	eax, BYTE PTR next_seq_to_send
	inc	eax
	cdq
	and	edx, 127				; 0000007fH
	add	eax, edx
	and	eax, 127				; 0000007fH
	sub	eax, edx
	mov	BYTE PTR next_seq_to_send, al

; 130  : 				has_packet = 0;

	mov	DWORD PTR has_packet$[rbp], 0

; 131  : 				if ((next_seq_to_send - acked_seq + MAX_SEQ) % MAX_SEQ >=WINDOW_SIZE) {

	movzx	eax, BYTE PTR next_seq_to_send
	movzx	ecx, BYTE PTR acked_seq
	sub	eax, ecx
	add	eax, 128				; 00000080H
	cdq
	and	edx, 127				; 0000007fH
	add	eax, edx
	and	eax, 127				; 0000007fH
	sub	eax, edx
	cmp	eax, 4
	jl	SHORT $LN12@main

; 132  : 					window_buzy = 1;

	mov	BYTE PTR window_buzy, 1
$LN12@main:
$LN11@main:

; 133  : 				}
; 134  : 			}
; 135  : 			break;

	jmp	$LN5@main
$LN13@main:

; 136  : 
; 137  : 		case PHYSICAL_LAYER_READY:   //物理层ready
; 138  : 			phl_ready = 1;

	mov	DWORD PTR phl_ready, 1

; 139  : 			if (has_packet && !window_buzy) {

	cmp	DWORD PTR has_packet$[rbp], 0
	je	SHORT $LN14@main
	movzx	eax, BYTE PTR window_buzy
	test	eax, eax
	jne	SHORT $LN14@main

; 140  : 				send_data_frame();

	call	send_data_frame
	npad	1

; 141  : 				next_seq_to_send = (next_seq_to_send + 1) % MAX_SEQ;

	movzx	eax, BYTE PTR next_seq_to_send
	inc	eax
	cdq
	and	edx, 127				; 0000007fH
	add	eax, edx
	and	eax, 127				; 0000007fH
	sub	eax, edx
	mov	BYTE PTR next_seq_to_send, al

; 142  : 				has_packet = 0;

	mov	DWORD PTR has_packet$[rbp], 0

; 143  : 				if ((next_seq_to_send - acked_seq + MAX_SEQ) % MAX_SEQ >=WINDOW_SIZE) {

	movzx	eax, BYTE PTR next_seq_to_send
	movzx	ecx, BYTE PTR acked_seq
	sub	eax, ecx
	add	eax, 128				; 00000080H
	cdq
	and	edx, 127				; 0000007fH
	add	eax, edx
	and	eax, 127				; 0000007fH
	sub	eax, edx
	cmp	eax, 4
	jl	SHORT $LN15@main

; 144  : 					window_buzy = 1;

	mov	BYTE PTR window_buzy, 1
$LN15@main:
$LN14@main:

; 145  : 				}
; 146  : 			}
; 147  : 			break;

	jmp	$LN5@main
$LN16@main:

; 148  : 
; 149  : 		case FRAME_RECEIVED: {
; 150  : 			int len = recv_frame((unsigned char *)&f, sizeof f);

	mov	edx, 264				; 00000108H
	lea	rcx, QWORD PTR f$[rbp]
	call	recv_frame
	mov	DWORD PTR len$5[rbp], eax

; 151  : 			if (len < 5 || crc32((unsigned char *)&f, len) != 0) {

	cmp	DWORD PTR len$5[rbp], 5
	jl	SHORT $LN18@main
	mov	edx, DWORD PTR len$5[rbp]
	lea	rcx, QWORD PTR f$[rbp]
	call	crc32
	test	eax, eax
	je	SHORT $LN17@main
$LN18@main:

; 152  : 				dbg_event("CRC error\n");

	lea	rcx, OFFSET FLAT:??_C@_0L@KKPDPFNK@CRC?5error?6@
	call	dbg_event
	npad	1

; 153  : 				break;

	jmp	$LN5@main
$LN17@main:

; 154  : 			}
; 155  : 
; 156  : 			// ========== 1. 处理确认信息（无论数据帧还是ACK帧） ==========
; 157  : 			unsigned char ack_num = f.ack;

	movzx	eax, BYTE PTR f$[rbp+1]
	mov	BYTE PTR ack_num$6[rbp], al

; 158  : 			// 累积确认：ack_num 表示对方期望的下一个序号，即已确认 ack_num-1 及之前的所有帧
; 159  : 			// 只有 ack_num 在 (acked_seq, next_seq] 范围内才有效
; 160  : 			if (seq_between(ack_num, acked_seq + 1, next_seq_to_send + 1)) {

	movzx	eax, BYTE PTR next_seq_to_send
	inc	eax
	movzx	ecx, BYTE PTR acked_seq
	inc	ecx
	movzx	r8d, al
	movzx	edx, cl
	movzx	ecx, BYTE PTR ack_num$6[rbp]
	call	seq_between
	test	eax, eax
	je	$LN19@main

; 161  : 				// 停止从 acked_seq 到 ack_num-1 的所有定时器
; 162  : 				for (unsigned char s = acked_seq; s != ack_num;

	movzx	eax, BYTE PTR acked_seq
	mov	BYTE PTR s$7[rbp], al
	jmp	SHORT $LN9@main
$LN7@main:

; 163  : 				     s = (s + 1) % MAX_SEQ) {

	movzx	eax, BYTE PTR s$7[rbp]
	inc	eax
	cdq
	and	edx, 127				; 0000007fH
	add	eax, edx
	and	eax, 127				; 0000007fH
	sub	eax, edx
	mov	BYTE PTR s$7[rbp], al
$LN9@main:

; 161  : 				// 停止从 acked_seq 到 ack_num-1 的所有定时器
; 162  : 				for (unsigned char s = acked_seq; s != ack_num;

	movzx	eax, BYTE PTR s$7[rbp]
	movzx	ecx, BYTE PTR ack_num$6[rbp]
	cmp	eax, ecx
	je	SHORT $LN8@main

; 164  : 					if (timer_active[s]) {

	movzx	eax, BYTE PTR s$7[rbp]
	lea	rcx, OFFSET FLAT:timer_active
	movzx	eax, BYTE PTR [rcx+rax]
	test	eax, eax
	je	SHORT $LN20@main

; 165  : 						stop_timer(s);

	movzx	eax, BYTE PTR s$7[rbp]
	mov	ecx, eax
	call	stop_timer
	npad	1

; 166  : 						timer_active[s] = 0;

	movzx	eax, BYTE PTR s$7[rbp]
	mov	QWORD PTR $T8[rbp], rax
	cmp	QWORD PTR $T8[rbp], 128			; 00000080H
	jae	SHORT $LN30@main
	jmp	SHORT $LN31@main
$LN30@main:
	call	__report_rangecheckfailure
	npad	1
$LN31@main:
	lea	rax, OFFSET FLAT:timer_active
	mov	rcx, QWORD PTR $T8[rbp]
	mov	BYTE PTR [rax+rcx], 0
$LN20@main:

; 167  : 					}
; 168  : 				}

	jmp	$LN7@main
$LN8@main:

; 169  : 				// 滑动窗口下沿到 ack_num
; 170  : 				acked_seq = ack_num;

	movzx	eax, BYTE PTR ack_num$6[rbp]
	mov	BYTE PTR acked_seq, al

; 171  : 				// 窗口可能不再满，允许网络层继续发送
; 172  : 				window_buzy = 0;

	mov	BYTE PTR window_buzy, 0
$LN19@main:

; 173  : 				// 如果你在主循环末尾集中控制网络层，这里可以不做 enable，只更新 window_busy 即可
; 174  : 			}
; 175  : 
; 176  : 			// ========== 2. 如果是数据帧，处理接收 ==========
; 177  : 			if (f.kind == FRAME_DATA) {

	movzx	eax, BYTE PTR f$[rbp]
	cmp	eax, 1
	jne	SHORT $LN21@main

; 178  : 				dbg_frame("Recv DATA seq=%d ack=%d pktID=%d\n",

	movsx	eax, WORD PTR f$[rbp+3]
	movzx	ecx, BYTE PTR f$[rbp+1]
	movzx	edx, BYTE PTR f$[rbp+2]
	mov	r9d, eax
	mov	r8d, ecx
	lea	rcx, OFFSET FLAT:??_C@_0CC@KIILNDNP@Recv?5DATA?5seq?$DN?$CFd?5ack?$DN?$CFd?5pktID?$DN?$CF@
	call	dbg_frame
	npad	1

; 179  : 					  f.seq, f.ack, *(short *)f.data);
; 180  : 				if (f.seq == excepted_seq) {

	movzx	eax, BYTE PTR f$[rbp+2]
	movzx	ecx, BYTE PTR excepted_seq
	cmp	eax, ecx
	jne	SHORT $LN23@main

; 181  : 					// 正确接收，上交分组
; 182  : 					put_packet(

	mov	edx, 256				; 00000100H
	lea	rcx, QWORD PTR f$[rbp+3]
	call	put_packet
	npad	1

; 183  : 						f.data,
; 184  : 						PKT_LEN); // 注意原样例中用 len-7，但固定长度用 PKT_LEN 更安全
; 185  : 					excepted_seq =

	movzx	eax, BYTE PTR excepted_seq
	inc	eax
	cdq
	and	edx, 127				; 0000007fH
	add	eax, edx
	and	eax, 127				; 0000007fH
	sub	eax, edx
	mov	BYTE PTR excepted_seq, al

; 186  : 						(excepted_seq + 1) % MAX_SEQ;
; 187  : 					// 发送 ACK，确认收到的帧（发送期望序号）
; 188  : 					send_ack_frame(excepted_seq);

	movzx	ecx, BYTE PTR excepted_seq
	call	send_ack_frame
	npad	1
$LN23@main:

; 189  : 				} else {
; 190  : 					// 乱序或重复帧，Go-Back-N 丢弃，可发送一个重复 ACK 提醒对方
; 191  : 					// 可选：send_ack_frame(expected_seq);
; 192  : 				}
; 193  : 			}

	jmp	SHORT $LN22@main
$LN21@main:

; 194  : 			// ========== 3. 如果是 ACK 帧，无需额外处理，确认已在第一步完成 ==========
; 195  : 			else if (f.kind == FRAME_ACK) {

	movzx	eax, BYTE PTR f$[rbp]
	cmp	eax, 2
	jne	SHORT $LN25@main

; 196  : 				dbg_frame("Recv ACK ack=%d\n", f.ack);

	movzx	eax, BYTE PTR f$[rbp+1]
	mov	edx, eax
	lea	rcx, OFFSET FLAT:??_C@_0BB@KGDEPFAN@Recv?5ACK?5ack?$DN?$CFd?6@
	call	dbg_frame
	npad	1
$LN25@main:
$LN22@main:

; 197  : 				// 确认信息已在第一步处理，这里只打印
; 198  : 			}
; 199  : 			break;

	jmp	SHORT $LN5@main
$LN26@main:

; 200  : 		}
; 201  : 
; 202  : 		case DATA_TIMEOUT:   //超时
; 203  : 			dbg_event("---- DATA %d timeout\n", arg);

	mov	edx, DWORD PTR arg$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_0BG@CGEOBPGK@?9?9?9?9?5DATA?5?$CFd?5timeout?6@
	call	dbg_event
	npad	1

; 204  : 			retransmit_all();

	call	retransmit_all
	npad	1
$LN5@main:

; 205  : 			break;
; 206  : 		}
; 207  : 
; 208  : 		if (!window_buzy && phl_ready)

	movzx	eax, BYTE PTR window_buzy
	test	eax, eax
	jne	SHORT $LN27@main
	cmp	DWORD PTR phl_ready, 0
	je	SHORT $LN27@main

; 209  : 			enable_network_layer();

	call	enable_network_layer
	npad	1
	jmp	SHORT $LN28@main
$LN27@main:

; 210  : 		else
; 211  : 			disable_network_layer();

	call	disable_network_layer
	npad	1
$LN28@main:

; 212  : 	}

	jmp	$LN2@main
$LN29@main:

; 213  : }

	lea	rcx, QWORD PTR [rbp-32]
	lea	rdx, OFFSET FLAT:main$rtcFrameData
	call	_RTC_CheckStackVars
	mov	rcx, QWORD PTR __$ArrayPad$[rbp]
	xor	rcx, rbp
	call	__security_check_cookie
	lea	rsp, QWORD PTR [rbp+952]
	pop	rdi
	pop	rbp
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\Users\34021\Downloads\Lab1(Win+Linux)\Lab1-2024(Win+Linux)\Lab1-Windows-VS2019\datalink.c
;	COMDAT retransmit_all
_TEXT	SEGMENT
seq$ = 4
f$1 = 40
$T2 = 264
retransmit_all PROC					; COMDAT

; 88   : {

	push	rbp
	push	rdi
	sub	rsp, 328				; 00000148H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__3E4772AE_datalink@c
	call	__CheckForDebuggerJustMyCode
	npad	1

; 89   : 	unsigned char seq = acked_seq;

	movzx	eax, BYTE PTR acked_seq
	mov	BYTE PTR seq$[rbp], al
$LN2@retransmit:

; 90   : 	while (seq != next_seq_to_send) {

	movzx	eax, BYTE PTR seq$[rbp]
	movzx	ecx, BYTE PTR next_seq_to_send
	cmp	eax, ecx
	je	$LN3@retransmit

; 91   : 		if (timer_active[seq]) {

	movzx	eax, BYTE PTR seq$[rbp]
	lea	rcx, OFFSET FLAT:timer_active
	movzx	eax, BYTE PTR [rcx+rax]
	test	eax, eax
	je	SHORT $LN4@retransmit

; 92   : 			stop_timer(seq); // 先停止旧的定时器

	movzx	eax, BYTE PTR seq$[rbp]
	mov	ecx, eax
	call	stop_timer
	npad	1

; 93   : 			timer_active[seq] = 0;

	movzx	eax, BYTE PTR seq$[rbp]
	mov	QWORD PTR $T2[rbp], rax
	cmp	QWORD PTR $T2[rbp], 128			; 00000080H
	jae	SHORT $LN6@retransmit
	jmp	SHORT $LN7@retransmit
$LN6@retransmit:
	call	__report_rangecheckfailure
	npad	1
$LN7@retransmit:
	lea	rax, OFFSET FLAT:timer_active
	mov	rcx, QWORD PTR $T2[rbp]
	mov	BYTE PTR [rax+rcx], 0
$LN4@retransmit:

; 94   : 		}
; 95   : 		dbg_event("Retransmit seq=%d\n", seq);

	movzx	eax, BYTE PTR seq$[rbp]
	mov	edx, eax
	lea	rcx, OFFSET FLAT:??_C@_0BD@FIILIENI@Retransmit?5seq?$DN?$CFd?6@
	call	dbg_event
	npad	1

; 96   : 		// 从缓存中取出帧重新发送
; 97   : 		struct FRAME *f = &send_buffer[seq];

	movzx	eax, BYTE PTR seq$[rbp]
	imul	rax, rax, 264				; 00000108H
	lea	rcx, OFFSET FLAT:send_buffer
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR f$1[rbp], rax

; 98   : 		put_frame((unsigned char *)f, 3 + PKT_LEN);

	mov	edx, 259				; 00000103H
	mov	rcx, QWORD PTR f$1[rbp]
	call	put_frame
	npad	1

; 99   : 		start_timer(seq, DATA_TIMER);

	movzx	eax, BYTE PTR seq$[rbp]
	mov	edx, 2000				; 000007d0H
	mov	ecx, eax
	call	start_timer
	npad	1

; 100  : 		timer_active[seq] = 1;

	movzx	eax, BYTE PTR seq$[rbp]
	lea	rcx, OFFSET FLAT:timer_active
	mov	BYTE PTR [rcx+rax], 1

; 101  : 		seq = (seq + 1) % MAX_SEQ;

	movzx	eax, BYTE PTR seq$[rbp]
	inc	eax
	cdq
	and	edx, 127				; 0000007fH
	add	eax, edx
	and	eax, 127				; 0000007fH
	sub	eax, edx
	mov	BYTE PTR seq$[rbp], al

; 102  : 	}

	jmp	$LN2@retransmit
$LN3@retransmit:
$LN5@retransmit:

; 103  : }

	lea	rsp, QWORD PTR [rbp+296]
	pop	rdi
	pop	rbp
	ret	0
retransmit_all ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\Users\34021\Downloads\Lab1(Win+Linux)\Lab1-2024(Win+Linux)\Lab1-Windows-VS2019\datalink.c
;	COMDAT seq_between
_TEXT	SEGMENT
tv73 = 192
tv80 = 192
a$ = 240
start$ = 248
end$ = 256
seq_between PROC					; COMDAT

; 79   : {

	mov	BYTE PTR [rsp+24], r8b
	mov	BYTE PTR [rsp+16], dl
	mov	BYTE PTR [rsp+8], cl
	push	rbp
	push	rdi
	sub	rsp, 248				; 000000f8H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__3E4772AE_datalink@c
	call	__CheckForDebuggerJustMyCode
	npad	1

; 80   : 	if (start <= end)

	movzx	eax, BYTE PTR start$[rbp]
	movzx	ecx, BYTE PTR end$[rbp]
	cmp	eax, ecx
	jg	SHORT $LN2@seq_betwee

; 81   : 		return start <= a && a < end;

	movzx	eax, BYTE PTR start$[rbp]
	movzx	ecx, BYTE PTR a$[rbp]
	cmp	eax, ecx
	jg	SHORT $LN5@seq_betwee
	movzx	eax, BYTE PTR a$[rbp]
	movzx	ecx, BYTE PTR end$[rbp]
	cmp	eax, ecx
	jge	SHORT $LN5@seq_betwee
	mov	DWORD PTR tv73[rbp], 1
	jmp	SHORT $LN6@seq_betwee
$LN5@seq_betwee:
	mov	DWORD PTR tv73[rbp], 0
$LN6@seq_betwee:
	mov	eax, DWORD PTR tv73[rbp]
	jmp	SHORT $LN1@seq_betwee
	jmp	SHORT $LN3@seq_betwee
$LN2@seq_betwee:

; 82   : 	else
; 83   : 		return a >= start || a < end;

	movzx	eax, BYTE PTR a$[rbp]
	movzx	ecx, BYTE PTR start$[rbp]
	cmp	eax, ecx
	jge	SHORT $LN7@seq_betwee
	movzx	eax, BYTE PTR a$[rbp]
	movzx	ecx, BYTE PTR end$[rbp]
	cmp	eax, ecx
	jl	SHORT $LN7@seq_betwee
	mov	DWORD PTR tv80[rbp], 0
	jmp	SHORT $LN8@seq_betwee
$LN7@seq_betwee:
	mov	DWORD PTR tv80[rbp], 1
$LN8@seq_betwee:
	mov	eax, DWORD PTR tv80[rbp]
$LN3@seq_betwee:
$LN1@seq_betwee:

; 84   : }

	lea	rsp, QWORD PTR [rbp+216]
	pop	rdi
	pop	rbp
	ret	0
seq_between ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\Users\34021\Downloads\Lab1(Win+Linux)\Lab1-2024(Win+Linux)\Lab1-Windows-VS2019\datalink.c
;	COMDAT send_ack_frame
_TEXT	SEGMENT
s$ = 16
__$ArrayPad$ = 488
ack$ = 528
send_ack_frame PROC					; COMDAT

; 66   : {

	mov	BYTE PTR [rsp+8], cl
	push	rbp
	push	rdi
	sub	rsp, 536				; 00000218H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rdi, QWORD PTR [rsp+32]
	mov	ecx, 78					; 0000004eH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	movzx	ecx, BYTE PTR [rsp+568]
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rbp
	mov	QWORD PTR __$ArrayPad$[rbp], rax
	lea	rcx, OFFSET FLAT:__3E4772AE_datalink@c
	call	__CheckForDebuggerJustMyCode
	npad	1

; 67   : 	struct FRAME s;
; 68   : 
; 69   : 	s.kind = FRAME_ACK;

	mov	BYTE PTR s$[rbp], 2

; 70   : 	s.ack = ack; //到时候再决定吧

	movzx	eax, BYTE PTR ack$[rbp]
	mov	BYTE PTR s$[rbp+1], al

; 71   : 
; 72   : 	dbg_frame("Send ACK  %d\n", s.ack);

	movzx	eax, BYTE PTR s$[rbp+1]
	mov	edx, eax
	lea	rcx, OFFSET FLAT:??_C@_0O@MEIGFFMO@Send?5ACK?5?5?$CFd?6@
	call	dbg_frame
	npad	1

; 73   : 
; 74   : 	put_frame((unsigned char *)&s, 2);

	mov	edx, 2
	lea	rcx, QWORD PTR s$[rbp]
	call	put_frame
	npad	1

; 75   : }

	lea	rcx, QWORD PTR [rbp-32]
	lea	rdx, OFFSET FLAT:send_ack_frame$rtcFrameData
	call	_RTC_CheckStackVars
	mov	rcx, QWORD PTR __$ArrayPad$[rbp]
	xor	rcx, rbp
	call	__security_check_cookie
	lea	rsp, QWORD PTR [rbp+504]
	pop	rdi
	pop	rbp
	ret	0
send_ack_frame ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\Users\34021\Downloads\Lab1(Win+Linux)\Lab1-2024(Win+Linux)\Lab1-Windows-VS2019\datalink.c
;	COMDAT send_data_frame
_TEXT	SEGMENT
s$ = 16
__$ArrayPad$ = 488
send_data_frame PROC					; COMDAT

; 45   : {

	push	rbp
	push	rsi
	push	rdi
	sub	rsp, 528				; 00000210H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rdi, QWORD PTR [rsp+32]
	mov	ecx, 76					; 0000004cH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rbp
	mov	QWORD PTR __$ArrayPad$[rbp], rax
	lea	rcx, OFFSET FLAT:__3E4772AE_datalink@c
	call	__CheckForDebuggerJustMyCode
	npad	1

; 46   : 	struct FRAME s;
; 47   : 
; 48   : 	s.kind = FRAME_DATA;

	mov	BYTE PTR s$[rbp], 1

; 49   : 	s.seq = next_seq_to_send;

	movzx	eax, BYTE PTR next_seq_to_send
	mov	BYTE PTR s$[rbp+2], al

; 50   : 	s.ack = excepted_seq; //暂时先这样,因为简化了，数据帧暂时不需要传递ack，ack只用单独的ack帧来传递

	movzx	eax, BYTE PTR excepted_seq
	mov	BYTE PTR s$[rbp+1], al

; 51   : 	memcpy(s.data, buffer, PKT_LEN);

	mov	r8d, 256				; 00000100H
	lea	rdx, OFFSET FLAT:buffer
	lea	rcx, QWORD PTR s$[rbp+3]
	call	memcpy
	npad	1

; 52   : 
; 53   : 	dbg_frame("Send DATA %d %d, ID %d\n", s.seq, s.ack, *(short *)s.data);

	movsx	eax, WORD PTR s$[rbp+3]
	movzx	ecx, BYTE PTR s$[rbp+1]
	movzx	edx, BYTE PTR s$[rbp+2]
	mov	r9d, eax
	mov	r8d, ecx
	lea	rcx, OFFSET FLAT:??_C@_0BI@GICFHJCA@Send?5DATA?5?$CFd?5?$CFd?0?5ID?5?$CFd?6@
	call	dbg_frame
	npad	1

; 54   : 
; 55   : 	    // 缓存帧副本（以备重传）
; 56   : 	send_buffer[next_seq_to_send] = s;

	movzx	eax, BYTE PTR next_seq_to_send
	imul	rax, rax, 264				; 00000108H
	lea	rcx, OFFSET FLAT:send_buffer
	lea	rdx, QWORD PTR s$[rbp]
	lea	rdi, QWORD PTR [rcx+rax]
	mov	rsi, rdx
	mov	ecx, 264				; 00000108H
	rep movsb

; 57   : 
; 58   : 	put_frame((unsigned char *)&s, 3 + PKT_LEN);

	mov	edx, 259				; 00000103H
	lea	rcx, QWORD PTR s$[rbp]
	call	put_frame
	npad	1

; 59   : 
; 60   : 	 // 启动该序号的定时器
; 61   : 	start_timer(next_seq_to_send, DATA_TIMER);

	movzx	eax, BYTE PTR next_seq_to_send
	mov	edx, 2000				; 000007d0H
	mov	ecx, eax
	call	start_timer
	npad	1

; 62   : 	timer_active[next_seq_to_send] = 1;

	movzx	eax, BYTE PTR next_seq_to_send
	lea	rcx, OFFSET FLAT:timer_active
	mov	BYTE PTR [rcx+rax], 1

; 63   : }

	lea	rcx, QWORD PTR [rbp-32]
	lea	rdx, OFFSET FLAT:send_data_frame$rtcFrameData
	call	_RTC_CheckStackVars
	mov	rcx, QWORD PTR __$ArrayPad$[rbp]
	xor	rcx, rbp
	call	__security_check_cookie
	lea	rsp, QWORD PTR [rbp+496]
	pop	rdi
	pop	rsi
	pop	rbp
	ret	0
send_data_frame ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\Users\34021\Downloads\Lab1(Win+Linux)\Lab1-2024(Win+Linux)\Lab1-Windows-VS2019\datalink.c
;	COMDAT put_frame
_TEXT	SEGMENT
frame$ = 224
len$ = 232
put_frame PROC						; COMDAT

; 38   : {

	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__3E4772AE_datalink@c
	call	__CheckForDebuggerJustMyCode
	npad	1

; 39   : 	*(unsigned int *)(frame + len) = crc32(frame, len);

	mov	edx, DWORD PTR len$[rbp]
	mov	rcx, QWORD PTR frame$[rbp]
	call	crc32
	movsxd	rcx, DWORD PTR len$[rbp]
	mov	rdx, QWORD PTR frame$[rbp]
	mov	DWORD PTR [rdx+rcx], eax

; 40   : 	send_frame(frame, len + 4);

	mov	eax, DWORD PTR len$[rbp]
	add	eax, 4
	mov	edx, eax
	mov	rcx, QWORD PTR frame$[rbp]
	call	send_frame
	npad	1

; 41   : 	phl_ready = 0;

	mov	DWORD PTR phl_ready, 0

; 42   : }

	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
put_frame ENDP
_TEXT	ENDS
END
